### ISSUE TITLE
DK-5 Compatability

### ISSUE THREAD

**Issue by AverageMaker** [AxelTB/nejePrint#1]
Hi

Does your DK-8 have an Arduino on the rear? I have a DK-5 which doesn't, and have been trying to get this to work (using the USB of a Raspberry Pi). I get the menu up, but most of the buttons fail to work.

Could it be because the DK-5 doesn't have the Arduino board that perhaps this code is designed for? (Mine has a custom board that they put on the back, a DK3000 (as printed on the PCB))

Would be great to work with you to get my version working as well - I'd love to write it up on my blog and credit you for the code.

Thanks

**Comment by AxelTB** [comment]
Hi,
Custom board on mine too. I've never noticed anything arduino like.

Have you tried both the python and the shell version? 

Btw you can just set the serial port to 57600 baud and send a byte with value 0xF6 if it answer with ASCII "ep" it might be similar.

The file commands.txt contains all the commands I used.

**Comment by AverageMaker** [comment]
You have the custom board - that's good news then. Should be easier to work out what's going wrong.

Let me explain what I've done so far. I've installed the dependencies and copied your git files to my Raspberry Pi 3.

I've got the engraver powered up, using a powered USB hub to make sure the Pi doesn't crash out when the laser draws the power it needs. The engraver's motor power is on a separate PSU.

I starter printer.py, it finds the engraver (sometimes takes a couple of tries) and then I click 'load converted image' (using your test image for now). it says "sending converted.bmp to machine, please wait' and then 'Done!'.

The engraver moves about a bit, then stops. So I click print expecting it to engrave. it does nothing, the menu disappears for half a second and re-appears. The same thing happens if I choose 'send laser home', 'reset printer', 'preview' etc.

The only options that do something are 'Convert Image', 'Load converted image' and 'Set burning time'. So it feels like it's half way there, but it's not quite working as expected.

Any ideas why that might be? I'll try the bash version now and see if it's the same. (I don't have a normal Linux PC to try this on unfortunately).

Thanks

**Comment by AverageMaker** [comment]
![neje1](https://cloud.githubusercontent.com/assets/5518441/18786912/3bdd0878-8198-11e6-85d1-e19d03147e53.jpg)

Tried the bash script - here's what I saw on screen (attached) - the printer didn't move, it just ran straight to 'done'.

**Comment by AverageMaker** [comment]
I have since installed bc but the same result (just no bc error)

**Comment by AxelTB** [comment]
Are you using debian or raspbian or something like that? If so check your user is in the dialout group. I always forget this...

Try this (Install jpnevulator before):
Open both a root and a nonroot shell
From root:
stty 57600 < /dev/ttyUSB0
jpnevulator -rat /dev/ttyUSB0

From the nonroot:
echo -e "\xF6"

Jpnevulator should read something like "ep" every time you send a F6.

Let me know what happens

**Comment by AverageMaker** [comment]
Well, I think I somehow killed it. The controller's blue 'state' light is stuck on blue permanently, after cycling power and even trying on Windows again. no idea how I did that, but I can't get it to do anything now. Game over for me, thanks anyway :(

**Comment by AxelTB** [comment]
Strange, I messed up big time with mine and still works...

No way to check compatability now, I'll close this
