### ISSUE TITLE
Problem with engraving time

### ISSUE THREAD

**Issue by kszere** [AxelTB/nejePrint#3]
Hi.
I encountered a problem with the time engraving (printing intensity), because as I type 60 or 999 prints just do not see anything print on the sheet.

I have model DK-8-KZ.
Thanks.

**Comment by AxelTB** [comment]
HI,
I might need some more information to try and reproduce the bug...

BTW engraving time is between 1 and 240. It must be set with ready and powered machine, try sending it when is in Preview Mode.

**Comment by AxelTB** [comment]
I assume you used the Bash version.

It won't support burning time anymore.
Try the python version instead.
